name = "kpg-gramado-lp"

type = "javascript"
compatibility_date = "2024-01-01"

[env.production]
name = "kpg-gramado-lp"
routes = [
  { pattern = "gramado.kpgimoveis.com.br/*", zone_name = "kpgimoveis.com.br" },
  { pattern = "*.csrdesouza.workers.dev/*" }
]

[docs.observability.enabled]
enabled = false
